### ISSUE TITLE
Launching a game without specifying an IP address

### ISSUE THREAD

**Issue by TwitchPlaysBF2** [cetteup/joinme.click-launcher#3]
As mentioned in Discord, would be cool to have a protocol handler that just allows starting the game. Should also consider any configured config.yaml settings.

i.e. `bf2://launch` would just end up opening the game.

**Comment by cetteup** [comment]
This will be part of the next release. Current plan is to add URL "actions", marked as `bf2://act/launch` for example.

**Comment by cetteup** [comment]
Implemented with the aforementioned action URL pattern.
